DROP SCHEMA IF EXISTS api CASCADE;

CREATE SCHEMA api;

CREATE TABLE api.event (
	event_id		SERIAL PRIMARY KEY,
	event_start	TIMESTAMP WITHOUT TIME ZONE	NOT NULL DEFAULT now(),
	event_end	TIMESTAMP WITHOUT TIME ZONE	NOT NULL DEFAULT now(),
	title		VARCHAR(255)			NOT NULL,
	entry_limit 	INTEGER				NOT NULL DEFAULT 1
);

CREATE TABLE api.entry (
	entry_id		SERIAL PRIMARY KEY,
	firstname	VARCHAR(255)		NOT NULL,
	lastname	VARCHAR(255)		NOT NULL,
	phone		VARCHAR(255)		NOT NULL,
	email		VARCHAR(255)		NOT NULL,
	event_id	INTEGER			NOT NULL REFERENCES api.event
);

