<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace AppBundle\Db\ApiSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Event
 *
 * Structure class for relation api.event.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Event extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('api.event')
            ->setPrimaryKey(['event_id'])
            ->addField('event_id', 'int4')
            ->addField('event_start', 'timestamp')
            ->addField('event_end', 'timestamp')
            ->addField('title', 'varchar')
            ->addField('entry_limit', 'int4')
            ;
    }
}
